name: Sync to Gitee
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Sync to Gitee
        uses: Yikun/hub-mirror-action@master
        with:
          src: github/An3035
          dst: gitee/zhangan11
          dst_name: zhangan11  # 关键：指定Gitee目标仓库名（和你的Gitee用户名一致）
          static_list: "An3035.github.io"
          dst_token: ${{ secrets.GITEE_TOKEN }}
          clone_style: https  # 关键：强制用HTTPS方式认证，不用SSH
          force_update: true
          debug: true
